### ISSUE TITLE
To-Do List for Release

### ISSUE THREAD

**Issue by Mahlarian** [Mahlarian/Sopharahsis#7]
# ⚡ Mandatory

- [ ] Audit system
- [x] Leveling system with rank cards
- [ ] Geometry Dash user and level search (by ID or name)
- [ ] Kick/Ban
- [ ] Mute/Unmute (with changeable mute role)
- [ ] Write the wiki 
- [ ] Minigame commands that allow for earning currency
- [ ] Currency system 
- [ ] Role add/remove/create command
- [ ] About user/server command

# 📣 Unconfirmed

- [ ] Timer command
- [ ] Derpibooru command
- [ ] Custom permissions for commands such as setaudit, editaudit, etc.
- [ ] Custom prefix by server
- [ ] Game stat commands (Suggest games in the comments!)
- [ ] URL Shortener
- [ ] Multiplayer Mine-sweeper
- [ ] Reputation system
- [ ] Connect four

# 🐛 Bugs

- [ ] The newgrounds link will break when searching for a level using one of default songs in the `gdsearch` command
- [ ] Searching for a level name will result in an error instead of searching for the level (Intended- Will be fixed soon)

**More features may be added before release!!**

**Comment by Mahlarian** [comment]
Help with this feature #5 may be required to get it added in for Release

**Comment by ghost** [comment]
For game stat commands, refer to my old checklist for some games to have commands for:
![image](https://user-images.githubusercontent.com/24266948/68539314-9753f280-03d5-11ea-832a-03bf8318feeb.png)

Some other ones I can think of are:
- Geometry Dash
- The Battle Royale games? Not my cup of tea, but probably plenty of others'.
- Literally any steam game, because you can at least get the playtime, achievements, stuff like that for those given a steam user ID / username.

**Comment by ghost** [comment]
Winning Minesweeper / Connect Four games should award currency to the owner of the last play of the game.

**Comment by Mahlarian** [comment]
> Winning Minesweeper / Connect Four games should award currency to the owner of the last play of the game.

I definitely think connect four should be like that, but for minesweeper, I take my inspiration from Keep Talking and Nobody Explodes, or, well, real bomb defusing squads.

Minesweeper should definitely be a collaborative effort, not competitive. However, to prevent cheap wins, I think you should get more currency for the more effort that you put into the game

As an example, if you win 100 currency from the game (total), player 1 does 65% of the work, player 2 does 30% of the work, and player 3 does 5% of the work, then player 1 gets 65 currency, player 2 gets 30 currency, and player 3 gets 5 currency.
